// Code generated by goyacc -o myparser.go -p my grammar.y. DO NOT EDIT.

//line grammar.y:4

// Autogenerated file - DO NOT EDIT
package myyacc

import __yyfmt__ "fmt"

//line grammar.y:8

import (
	"fmt"
	"github.com/xavier268/myprolog/config"
	"io"
)

//line grammar.y:20
type mySymType struct {
	yys int
	// define the SymType structure
	list  []Term // list of Terms
	value Term   // single Term
}
